---
servers:
- ip: 34.235.139.164
apps:
- name: hello-world-app
  packages:
  - name: apache2
    is-service: true #if true, app starts a service with the same name
  - name: php5
  - name: libapache2-mod-php5
  files:
  - path: /var/www/html/index.php
    mode: 644
    owner: root
    group: root
    content: |
      <?php

      header("Content-Type: text/plain");

      echo "Hello, world!\n";