---
servers:
- ip: 34.235.139.164
apps:
- name: hello-world-app
  packages:
  - name: apache2
    is-service: true #if true, app starts a service with the same name
  - name: php5
  - name: libapache2-mod-php5
  files:
  - path: /etc/apache2/mods-available/dir.conf
    mode: 644
    owner: root
    group: root
    content: |
      <IfModule mod_dir.c>
        DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
      </IfModule>
  - path: /var/www/html/index.php
    mode: 644
    owner: root
    group: root
    content: |
      <?php

      header("Content-Type: text/plain");

      echo "Hello, world2!\n";